---
- name: "Automate docker build using Ansible"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop flask-app
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm flask-app
    ignore_errors: yes
  
  - name: remove used image
    command: docker rmi mohamedmtolba/project-app
    ignore_errors: yes
    
  - name: build new image 
    command: docker build -t mohamedmtolba/project-app .

  - name: run new container
    command: docker run -it -d --name flask-app -p 5050:5000 mohamedmtolba/project-app

  - name: push docker image 
    command: docker push mohamedmtolba/project-app

