apiVersion: v1
kind: Service
metadata:
  name: service-app
  namespace: python-flask-app
  labels:
    app: flask-python-app
spec:
  selector:
    app: flask-python-app
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000